// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://czjojfifupluehzcuvmh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6am9qZmlmdXBsdWVoemN1dm1oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5OTA4ODgsImV4cCI6MjA1ODU2Njg4OH0.Gi3qwa-uGrTe8aYvKpOm2ro1PMWYLjROccYowRwqYp4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);